import Vehicle from "../models/Vehicle.js";

const defaultVehicles = [
  // ── Dhaka – inter-city buses ──────────────────────────────────────
  {
    name: "Hanif Enterprise 1",
    vehicleType: "Bus",
    route: "Dhaka → Cumilla → Feni → Chittagong",
    city: "Dhaka",
    registrationNumber: "DH-TA-11-1001",
    description: "AC express bus on the Dhaka–Chittagong highway.",
    averageSafetyScore: 4.3,
    totalRatings: 18,
  },
  {
    name: "Hanif Enterprise 2",
    vehicleType: "Bus",
    route: "Dhaka → Narsingdi → Brahmanbaria → Sylhet",
    city: "Dhaka",
    registrationNumber: "DH-TA-11-1002",
    description: "Non-AC coach via the eastern highway to Sylhet.",
    averageSafetyScore: 3.8,
    totalRatings: 12,
  },
  {
    name: "Green Line Paribahan 1",
    vehicleType: "Bus",
    route: "Dhaka → Tongi → Mymensingh → Jamalpur",
    city: "Dhaka",
    registrationNumber: "DH-TA-11-2001",
    description: "AC sleeper coach on the northern corridor.",
    averageSafetyScore: 4.6,
    totalRatings: 25,
  },
  {
    name: "Green Line Paribahan 2",
    vehicleType: "Bus",
    route: "Dhaka → Manikganj → Sirajganj → Rajshahi",
    city: "Dhaka",
    registrationNumber: "DH-TA-11-2002",
    description: "Overnight express to Rajshahi via Jamuna Bridge.",
    averageSafetyScore: 4.2,
    totalRatings: 20,
  },
  {
    name: "Shyamoli Paribahan 1",
    vehicleType: "Bus",
    route: "Dhaka → Mawa → Madaripur → Barishal",
    city: "Dhaka",
    registrationNumber: "DH-TA-11-2003",
    description: "Southern highway express via Padma crossing.",
    averageSafetyScore: 4.0,
    totalRatings: 14,
  },
  {
    name: "Shyamoli Paribahan 2",
    vehicleType: "Bus",
    route: "Dhaka → Manikganj → Faridpur → Jessore → Khulna",
    city: "Dhaka",
    registrationNumber: "DH-TA-11-2004",
    description: "Long-haul AC coach to Khulna via the southwest corridor.",
    averageSafetyScore: 3.9,
    totalRatings: 11,
  },
  {
    name: "Ena Transport 1",
    vehicleType: "Bus",
    route: "Mirpur → Farmgate → Shahbagh → Motijheel",
    city: "Dhaka",
    registrationNumber: "DH-TA-11-3001",
    description: "City bus on the Mirpur–Motijheel inner corridor.",
    averageSafetyScore: 4.1,
    totalRatings: 30,
  },
  {
    name: "Ena Transport 2",
    vehicleType: "Bus",
    route: "Uttara → Airport Road → Kawran Bazar → Sadarghat",
    city: "Dhaka",
    registrationNumber: "DH-TA-11-3002",
    description: "Cross-city bus from Uttara to Sadarghat river terminal.",
    averageSafetyScore: 3.9,
    totalRatings: 22,
  },
  {
    name: "BRTC City Bus 1",
    vehicleType: "Bus",
    route: "Gulshan → Rampura → Demra → Jatrabari",
    city: "Dhaka",
    registrationNumber: "DH-BRTC-0101",
    description: "Government BRTC double-decker on the eastern ring.",
    averageSafetyScore: 4.5,
    totalRatings: 40,
  },
  {
    name: "BRTC City Bus 2",
    vehicleType: "Bus",
    route: "Mohakhali → Tejgaon → Malibagh → Demra",
    city: "Dhaka",
    registrationNumber: "DH-BRTC-0102",
    description: "BRTC service through the industrial belt.",
    averageSafetyScore: 4.2,
    totalRatings: 15,
  },
  {
    name: "Soudia Paribahan",
    vehicleType: "Bus",
    route: "Dhaka → Kanchpur → Nabinagar → Sylhet",
    city: "Dhaka",
    registrationNumber: "DH-TA-11-4001",
    description: "Economy non-stop to Sylhet via the N2 highway.",
    averageSafetyScore: 3.5,
    totalRatings: 9,
  },
  // ── Dhaka – metro & taxi ──────────────────────────────────────────
  {
    name: "Dhaka Metro MRT-6 S1",
    vehicleType: "Metro",
    route: "Uttara North → Agargaon → Farmgate → Motijheel",
    city: "Dhaka",
    registrationNumber: "MRT-6-S01",
    description: "MRT Line 6 — Dhaka's first metro rail set.",
    averageSafetyScore: 4.9,
    totalRatings: 85,
  },
  {
    name: "Dhaka Metro MRT-6 S2",
    vehicleType: "Metro",
    route: "Diabari → Pallabi → Mirpur-10 → Kamalapur",
    city: "Dhaka",
    registrationNumber: "MRT-6-S02",
    description: "MRT Line 6 extension set serving Mirpur corridor.",
    averageSafetyScore: 4.8,
    totalRatings: 62,
  },
  {
    name: "Pathao Ride CNG-01",
    vehicleType: "Taxi",
    route: "Dhanmondi → Science Lab → Shahbagh → Badda",
    city: "Dhaka",
    registrationNumber: "DH-TA-GA-0501",
    description: "App-based CNG auto on the Dhanmondi–Badda corridor.",
    averageSafetyScore: 3.6,
    totalRatings: 14,
  },
  {
    name: "Uber Dhaka X-01",
    vehicleType: "Taxi",
    route: "Gulshan → Banani → Mohakhali → Karwan Bazar",
    city: "Dhaka",
    registrationNumber: "DH-TA-GA-0502",
    description: "Ride-share sedan on the northern business belt.",
    averageSafetyScore: 4.4,
    totalRatings: 28,
  },

  // ── Chittagong ────────────────────────────────────────────────────
  {
    name: "S Alam Paribahan 1",
    vehicleType: "Bus",
    route: "Chittagong → Feni → Cumilla → Dhaka",
    city: "Chittagong",
    registrationNumber: "CH-TA-11-4001",
    description: "Premium AC coach returning Chittagong to Dhaka.",
    averageSafetyScore: 4.4,
    totalRatings: 20,
  },
  {
    name: "S Alam Paribahan 2",
    vehicleType: "Bus",
    route: "Chittagong → Patiya → Lohagara → Chakaria → Cox's Bazar",
    city: "Chittagong",
    registrationNumber: "CH-TA-11-4002",
    description: "Tourist AC bus to Cox's Bazar beach resort.",
    averageSafetyScore: 4.8,
    totalRatings: 35,
  },
  {
    name: "Chittagong BRTC City",
    vehicleType: "Bus",
    route: "Agrabad → Chawkbazar → GEC Circle → Pahartali",
    city: "Chittagong",
    registrationNumber: "CH-BRTC-0201",
    description: "City service covering major Chittagong commercial zones.",
    averageSafetyScore: 3.7,
    totalRatings: 8,
  },
  {
    name: "Soudia CH–COX",
    vehicleType: "Bus",
    route: "Chittagong → Ramu → Teknaf → Cox's Bazar",
    city: "Chittagong",
    registrationNumber: "CH-TA-11-4003",
    description: "Non-AC express for the coastal southern route.",
    averageSafetyScore: 3.4,
    totalRatings: 6,
  },
  {
    name: "Chittagong CNG Taxi",
    vehicleType: "Taxi",
    route: "Port Area → Nasirabad → Oxygen → Shah Amanat Airport",
    city: "Chittagong",
    registrationNumber: "CH-TA-GA-0601",
    description: "CNG auto-rickshaw linking the port to the airport.",
    averageSafetyScore: 3.3,
    totalRatings: 5,
  },

  // ── Sylhet ────────────────────────────────────────────────────────
  {
    name: "Shyamoli SYL-1",
    vehicleType: "Bus",
    route: "Sylhet → Habiganj → Brahmanbaria → Dhaka",
    city: "Sylhet",
    registrationNumber: "SL-TA-11-5001",
    description: "Non-stop AC return bus on the Sylhet–Dhaka highway.",
    averageSafetyScore: 4.0,
    totalRatings: 16,
  },
  {
    name: "Sylhet City Minibus",
    vehicleType: "Bus",
    route: "Sylhet → Srimangal → Moulvibazar → Sunamganj",
    city: "Sylhet",
    registrationNumber: "SL-TA-11-5002",
    description: "Tea-garden route through the Sreemangal midpoint.",
    averageSafetyScore: 3.4,
    totalRatings: 6,
  },
  {
    name: "Ena SYL Express",
    vehicleType: "Bus",
    route: "Sylhet → Sherpur → Nabiganj → Lakshmipur",
    city: "Sylhet",
    registrationNumber: "SL-TA-11-5003",
    description: "Regional connector through eastern Sylhet division.",
    averageSafetyScore: 3.1,
    totalRatings: 4,
  },

  // ── Rajshahi ──────────────────────────────────────────────────────
  {
    name: "Rajshahi Express 1",
    vehicleType: "Bus",
    route: "Rajshahi → Sirajganj → Tangail → Dhaka",
    city: "Rajshahi",
    registrationNumber: "RJ-TA-11-6001",
    description: "Overnight AC bus connecting Rajshahi to Dhaka.",
    averageSafetyScore: 4.2,
    totalRatings: 11,
  },
  {
    name: "Barind Paribahan",
    vehicleType: "Bus",
    route: "Rajshahi → Natore → Pabna → Ishwardi",
    city: "Rajshahi",
    registrationNumber: "RJ-TA-11-6002",
    description: "Local service through the north-western agricultural belt.",
    averageSafetyScore: 3.1,
    totalRatings: 4,
  },
  {
    name: "Rajshahi City BRTC",
    vehicleType: "Bus",
    route: "Rajshahi Station → Shaheb Bazar → Upashahar → Kazla",
    city: "Rajshahi",
    registrationNumber: "RJ-BRTC-0301",
    description: "Government city bus on the Rajshahi inner ring.",
    averageSafetyScore: 3.8,
    totalRatings: 7,
  },

  // ── Khulna ────────────────────────────────────────────────────────
  {
    name: "Soukhin Paribahan 1",
    vehicleType: "Bus",
    route: "Khulna → Jessore → Magura → Faridpur → Dhaka",
    city: "Khulna",
    registrationNumber: "KL-TA-11-7001",
    description: "Premium overnight coach on the southwest highway.",
    averageSafetyScore: 4.3,
    totalRatings: 13,
  },
  {
    name: "Soukhin Paribahan 2",
    vehicleType: "Bus",
    route: "Khulna → Bagerhat → Morrelganj → Pirojpur",
    city: "Khulna",
    registrationNumber: "KL-TA-11-7002",
    description: "Coastal service near the Sundarbans buffer zone.",
    averageSafetyScore: 3.6,
    totalRatings: 7,
  },
  {
    name: "Khulna City Bus",
    vehicleType: "Bus",
    route: "Khulna Station → Dakbangla → Boyra → Rupsha",
    city: "Khulna",
    registrationNumber: "KL-BRTC-0401",
    description: "Inner-city service covering Khulna's main commercial areas.",
    averageSafetyScore: 3.5,
    totalRatings: 5,
  },

  // ── Barishal ──────────────────────────────────────────────────────
  {
    name: "Barishal Express 1",
    vehicleType: "Bus",
    route: "Barishal → Gopalganj → Madaripur → Mawa → Dhaka",
    city: "Barishal",
    registrationNumber: "BR-TA-11-8001",
    description: "AC coach connecting Barishal to Dhaka via Padma crossing.",
    averageSafetyScore: 3.9,
    totalRatings: 9,
  },
  {
    name: "Barishal Coastal Bus",
    vehicleType: "Bus",
    route: "Barishal → Bhola → Lakshmipur → Noakhali",
    city: "Barishal",
    registrationNumber: "BR-TA-11-8002",
    description: "Coastal connector through the Meghna estuary belt.",
    averageSafetyScore: 3.2,
    totalRatings: 4,
  },

  // ── Mymensingh ────────────────────────────────────────────────────
  {
    name: "Mymensingh Express 1",
    vehicleType: "Bus",
    route: "Mymensingh → Gazipur → Tongi → Dhaka",
    city: "Mymensingh",
    registrationNumber: "MY-TA-11-9001",
    description: "Economy bus on the Mymensingh–Dhaka arterial road.",
    averageSafetyScore: 3.5,
    totalRatings: 6,
  },
  {
    name: "Mymensingh Local 2",
    vehicleType: "Bus",
    route: "Mymensingh → Kishoreganj → Bhairab → Ashuganj",
    city: "Mymensingh",
    registrationNumber: "MY-TA-11-9002",
    description: "Regional bus across eastern Mymensingh division.",
    averageSafetyScore: 3.0,
    totalRatings: 3,
  },

  // ── Cumilla ───────────────────────────────────────────────────────
  {
    name: "Cumilla Express 1",
    vehicleType: "Bus",
    route: "Cumilla → Daudkandi → Narsingdi → Dhaka",
    city: "Comilla",
    registrationNumber: "CO-TA-11-1101",
    description: "Fast inter-district bus on the Dhaka–Chittagong corridor.",
    averageSafetyScore: 4.1,
    totalRatings: 17,
  },
  {
    name: "Cumilla Regional 2",
    vehicleType: "Bus",
    route: "Cumilla → Chandpur → Hajiganj → Lakshmipur",
    city: "Comilla",
    registrationNumber: "CO-TA-11-1102",
    description: "Local bus through the Meghna riverside districts.",
    averageSafetyScore: 3.4,
    totalRatings: 5,
  },

  // ── Narayanganj ───────────────────────────────────────────────────
  {
    name: "Narayanganj City 1",
    vehicleType: "Bus",
    route: "Narayanganj → Demra → Jatrabari → Gulistan → Dhaka",
    city: "Narayanganj",
    registrationNumber: "NR-TA-11-1201",
    description: "Short-haul urban bus linking Narayanganj to Dhaka.",
    averageSafetyScore: 3.8,
    totalRatings: 10,
  },
  {
    name: "Narayanganj River Bus",
    vehicleType: "Bus",
    route: "Narayanganj → Sonargaon → Munshiganj → Mawa",
    city: "Narayanganj",
    registrationNumber: "NR-TA-11-1202",
    description: "Scenic route through the historic Sonargaon midpoint.",
    averageSafetyScore: 4.0,
    totalRatings: 8,
  },

  // ── Bangladesh Railway ─────────────────────────────────────────────
  {
    name: "Subarna Express",
    vehicleType: "Train",
    route: "Dhaka Kamalapur → Cumilla → Feni → Chittagong",
    city: "Dhaka",
    registrationNumber: "BR-IC-701",
    description: "Intercity express flagship between Dhaka and Chittagong.",
    averageSafetyScore: 4.7,
    totalRatings: 60,
  },
  {
    name: "Parabat Express",
    vehicleType: "Train",
    route: "Dhaka Kamalapur → Akhaura → Habiganj → Sylhet",
    city: "Dhaka",
    registrationNumber: "BR-IC-709",
    description: "Intercity express to Sylhet through the eastern highlands.",
    averageSafetyScore: 4.5,
    totalRatings: 42,
  },
  {
    name: "Rupsha Express",
    vehicleType: "Train",
    route: "Dhaka → Rajbari → Kushtia → Chuadanga → Khulna",
    city: "Khulna",
    registrationNumber: "BR-IC-725",
    description: "Intercity service via the western rail line.",
    averageSafetyScore: 4.3,
    totalRatings: 28,
  },
  {
    name: "Tista Express",
    vehicleType: "Train",
    route: "Dhaka Kamalapur → Mymensingh → Jamalpur → Dewanganj",
    city: "Dhaka",
    registrationNumber: "BR-IC-751",
    description: "Northern intercity rail through the haor-flood belt.",
    averageSafetyScore: 4.1,
    totalRatings: 19,
  },
  {
    name: "Intercity Chittagong Mail",
    vehicleType: "Train",
    route: "Chittagong → Feni → Lakshmipur → Noakhali",
    city: "Chittagong",
    registrationNumber: "BR-IC-762",
    description: "Coastal rail service through the southeastern districts.",
    averageSafetyScore: 3.9,
    totalRatings: 14,
  },
];

export const seedVehicles = async () => {
  const count = await Vehicle.countDocuments();

  if (count > 0) {
    return;
  }

  await Vehicle.insertMany(defaultVehicles);
  console.log(`${defaultVehicles.length} Bangladeshi vehicles seeded successfully.`);
};
